site_name: MkDocs INI Includer Demo
site_description: Demonstration of the MkDocs INI Includer plugin
site_author: MkDocs INI Includer Team

# Repository
repo_url: https://github.com/example/mkdocs-ini-includer
repo_name: mkdocs-ini-includer

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.follow
    - search.highlight
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - search
  - ini-includer:
      base_path: "../config"
      config_file: "application.ini"

# Navigation
nav:
  - Home: index.md
  - Configuration:
    - Overview: config/overview.md
    - Database: config/database.md
    - Security: config/security.md
    - API: config/api.md
  - Examples:
    - Full Config: examples/full-config.md
    - Partial Includes: examples/partial-includes.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details